name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./c_sharp
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: 构建 .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: 构建依赖
      run: dotnet restore
    - name: 构建
      run:  dotnet build --no-restore
    - name: 测试
      run: dotnet test --no-build --verbosity normal
    - name: 执行
      run: dotnet run
